spring.application.name=ricceta-mia
spring.datasource.url=jdbc:postgresql://localhost:5432/ricceta-mia
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enable=tru
spring.flyway.locations=classpath:db/migration